#! /bin/sh
set -e

if [ ! -z "$2" ]; then
  if [ "$1" = upgrade ] && dpkg --compare-versions "$2" lt "11.04.1" ; then
    update-alternatives --quiet --remove-all firefox-homepage || true
  fi
fi

exit 0

